[package]
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
name = "eris"
version = "0.1.0"

[dependencies]
clap = "2.25.0"
curl = "0.4.7"
dotenv = "0.10.1"
error-chain = "0.10.0"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
serde_yaml = "0.7.1"
